version: '3.8'

services:
  firefly-bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: firefly-finance-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # File to store the prompt template
      - ./prompt.template:/app/prompt.template
    environment:
      - NODE_ENV=production 